# https://github.com/alacritty/alacritty-theme
general.import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"] #horizon-dark.toml"]

[font]
size = 15.7
normal = { family = "MonaspiceNe Nerd Font"}

[window]
padding = { x = 2, y = 2 }
dynamic_padding = true
opacity = 0.78
