# https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/themes/horizon-dark.toml"]

[font]
size = 14
normal = { family = "MonaspiceNe Nerd Font", style = "Regular"}

[shell]
program = "/bin/fish"

[window]
padding = { x = 3, y = 2 }
dynamic_padding = true
opacity = 0.78
